# restful api test file
@baseUrl = http://{{$processEnv WISERIP}}/api
@token = {{$processEnv WISERTOKEN}}
#@token = "1"

### claim token - press button on device!

POST {{baseUrl}}/account/claim
Content-Type: application/json

{
   "user": "apiuser"
}

### get info

GET {{baseUrl}}/info
Content-Type: application/json
Authorization: Bearer {{token}}

### get loads

GET {{baseUrl}}/loads
Content-Type: application/json
Authorization: Bearer {{token}}

### set load n tagetstate

PUT {{baseUrl}}/loads/1/target_state
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "bri": 10000
}

### set load n tagetstate

PUT {{baseUrl}}/loads/1/target_state
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "bri": 0
}

### set on load n

PUT {{baseUrl}}/loads/1/ctrl
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "button": "on",
   "event": "click"
}

### set off load n

PUT {{baseUrl}}/loads/1/ctrl
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "button": "off",
   "event": "click"
}

### get devices

GET {{baseUrl}}/devices
Content-Type: application/json
Authorization: Bearer {{token}}

### get site

GET {{baseUrl}}/site
Content-Type: application/json
Authorization: Bearer {{token}}

### get jobs

GET {{baseUrl}}/jobs
Content-Type: application/json
Authorization: Bearer {{token}}

### get accounts

GET {{baseUrl}}/account
Content-Type: application/json
Authorization: Bearer {{token}}

### set name of load n

PATCH {{baseUrl}}/loads/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "new name"
}